name: 🚀 Zstrategies Upload Files to Hostinger via SFTP

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 📤 Upload Files to Hostinger
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}  # or use `key:` if SSH key-based
          port: 22
          source: "."               # 👈 uploads all repo files
          target: ${{ secrets.REMOTE_DIR }}  # 👈 your Hostinger path
